'use strict';
/* Generates preview/preview.html from the shipped files, so the human-review
   gate always exercises the exact release bundle (CSS, templates, modules).
   Run:  node preview/build-preview.js            (from source tree)
         HNA_ROOT=<staged dir> node preview/build-preview.js   (from publish/)
   Output: preview/preview.html — a self-contained page. Never edit it by
   hand; regenerate instead. */

const fs = require('fs');
const path = require('path');

const ROOT = process.env.HNA_ROOT || path.resolve(__dirname, '..');
const OUT = path.join(__dirname, 'preview.html');

const TEMPLATES = ['Front.html', 'Back.html'];

/* Everything the templates reference — stylesheet <link href>s and module
   <script src>s — is DISCOVERED by reading the templates themselves, so
   adding or removing an asset needs no edit here and the preview's asset list
   can never drift from the shipped bundle. */
function discoverAssets() {
  const css = [];
  const js = [];
  const linkRe = /<link\b[^>]*\bhref="([^"]+)"/gi;
  const srcRe = /<script\b[^>]*\bsrc="([^"]+)"/gi;
  TEMPLATES.forEach((name) => {
    const html = fs.readFileSync(path.join(ROOT, name), 'utf8');
    let m;
    while ((m = linkRe.exec(html))) if (css.indexOf(m[1]) === -1) css.push(m[1]);
    while ((m = srcRe.exec(html))) if (js.indexOf(m[1]) === -1) js.push(m[1]);
  });
  return { css: css, js: js };
}

/* "_hna_typing.js" -> "typing" (the HNA_MODS key / MOD_ORDER name). */
function moduleKey(file) {
  return path.basename(file).replace(/\.[^.]+$/, '').split('_').filter(Boolean).pop();
}

const assets = discoverAssets();

/* Freshness gate: if preview.html already exists and is newer than every
   input (the shipped CSS/templates/modules AND this generator), the artifact
   reflects the current sources — skip the rewrite so preview.html's mtime
   stays a truthful "last build" stamp. tests/pre-flight.js asserts the
   artifact is never older than the working sources. */
if (fs.existsSync(OUT)) {
  const outM = fs.statSync(OUT).mtimeMs;
  const names = [].concat(assets.css, TEMPLATES, assets.js);
  let stale = false;
  names.forEach((name) => {
    const p = path.join(ROOT, name);
    if (fs.existsSync(p) && fs.statSync(p).mtimeMs > outM) stale = true;
  });
  if (!stale && fs.statSync(__filename).mtimeMs <= outM) {
    console.log('preview is up to date (' + OUT + ' is newer than all inputs) — skipping regeneration');
    process.exit(0);
  }
}

/* Embed a file's content as a JS string inside an inline <script> block.
   `</script>` would terminate the outer tag, so any `</` becomes `<\/`,
   which JS parses back to `</`. */
function embed(name) {
  const src = fs.readFileSync(path.join(ROOT, name), 'utf8');
  return JSON.stringify(src).replace(/<\//g, '<\\/');
}

const css = assets.css.map(embed).join('\n');
const front = embed(TEMPLATES[0]);
const back = embed(TEMPLATES[1]);
const modsObj = assets.js.map(function (f) {
  return '  ' + JSON.stringify(moduleKey(f)) + ': ' + embed(f);
}).join(',\n');
const modOrder = JSON.stringify(assets.js.map(moduleKey));

const preview = `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>HNA Card — Preview (generated)</title>
<!-- GENERATED FILE: regenerated by  node preview/build-preview.js  (or
     HNA_ROOT=<dir> node preview/build-preview.js). Do not edit by hand. -->
<style>
  html, body { margin: 0; padding: 0; height: 100%; background: #1a2026; font-family: Segoe UI, Arial, sans-serif; }
  #toolbar { position: fixed; top: 0; left: 0; right: 0; z-index: 999; display: flex; flex-wrap: wrap;
             gap: 6px; align-items: center; padding: 8px 12px; background: #2a323b; color: #dfe6ec;
             border-bottom: 1px solid #000; font-size: 13px; }
  #toolbar .sep { width: 1px; height: 22px; background: #4a545e; margin: 0 6px; }
  #toolbar button { background: #3a4652; color: #e8eef4; border: 1px solid #55636f; border-radius: 4px;
                    padding: 4px 10px; font-size: 12px; cursor: pointer; }
  #toolbar button:hover { background: #46576a; }
  #toolbar button.on { background: #1e6f4c; border-color: #2f9d6e; }
  #toolbar button:disabled { opacity: .45; cursor: default; }
  #toolbar label { color: #9fb2c3; margin-right: 4px; }
  #stageWrap { position: fixed; top: 52px; left: 0; right: 0; bottom: 0; overflow: auto; padding: 16px; }
  #stage { display: block; margin: 0 auto; width: 100%; height: calc(100vh - 86px); border: 1px solid #3a4652;
           background: #fff; box-shadow: 0 4px 24px rgba(0,0,0,.5); }
  #stage.w375 { width: 375px; }
  #stage.w768 { width: 768px; }
  #stage.w1200 { width: 1200px; }
</style>
</head>
<body>

<div id="toolbar">
  <button id="bFront" class="on">Mặt Trước</button>
  <button id="bBack">Mặt Sau</button>
  <div class="sep"></div>
  <button id="bNight">Chế độ Tối (Dark Mode)</button>
  <div class="sep"></div>
  <button data-w="375">Mobile</button>
  <button data-w="768">Tablet</button>
  <button data-w="1200" class="on">Desktop</button>
</div>

<div id="stageWrap">
  <iframe id="stage" title="HNA card preview"></iframe>
</div>

<script>
// ─────────────────────────────────────────────────────────────
// Embedded release assets (from the shipped files, verbatim).
// ─────────────────────────────────────────────────────────────
var HNA_CSS = ${css};
var TPL_FRONT = ${front};
var TPL_BACK = ${back};
var HNA_MODS = {
${modsObj}
};

// Sample note fields (mimics what Anki injects at render time).
var SAMPLE = {
  word: 'en liten katt som heter Misse och bor i Stockholm',
  meaning: 'ett litet svenskt husdjur som jamar högt på nätterna och sover i soffan hela eftermiddagen',
  pos: 'substantiv',
  transliteration: 'kat',
  example: 'Katten sover på soffan.',
  example_translated: 'The cat is sleeping on the sofa.',
  explain: 'Katten är ett av de vanligaste husdjuren i Sverige, och den jamar gärna när den är hungrig.',
  forms: 'katt, katten, katter, katterna',
  synonym: 'kisse, kattdjur',
  antonym: 'hund',
  tag_1: 'djur', tag_2: 'husdjur', tag_3: '', tag_4: '',
  Tags: '',
  ID: '42',
  image: '',
  audio_word: '[sound:word.mp3]', audio_meaning: '[sound:meaning.mp3]', audio_example: '[sound:example.mp3]'
};

// Mini-mustache (same contract as tests/harness.js).
function render(tpl, data) {
  tpl = tpl.replace(/\\{\\{type:word\\}\\}/g, '<center><input type="text" id="typeans" value=""></center>');
  var prev;
  do {
    prev = tpl;
    tpl = tpl.replace(/\\{\\{#([^}]+)\\}\\}([\\s\\S]*?)\\{\\{\\/\\1\\}\\}/g, function (m, k, inner) {
      var v = data[k];
      return (v !== undefined && v !== null && v !== '') ? render(inner, data) : '';
    });
  } while (tpl !== prev);
  tpl = tpl.replace(/\\{\\{([^}]+)\\}\\}/g, function (m, k) {
    return (data[k] !== undefined ? String(data[k]) : '');
  });
  return tpl;
}

// In the preview, the templates' own <link>/<script src> tags must not run
// (the assets are inlined here and injected in the exact load order).
// Inline <script> bodies are kept and executed after the modules.
function splitTemplate(tpl) {
  var html = tpl
    .replace(/<link\\s+[^>]*href="[^"]*"[^>]*>/g, '')
    .replace(/<script\\s+src="[^"]*"[^>]*><\\/script>/g, '');
  var inline = [];
  html = html.replace(/<script>([\\s\\S]*?)<\\/script>/g, function (m, body) {
    inline.push(body);
    return '';
  });
  return { html: html, inline: inline };
}

var stage = document.getElementById('stage');
var lastMode = 'meaning-word';
var face = 'front';
var nightMode = false;
var SAMPLE_TYPED = 'en liten katt som heter Misa och bor i Stockholm';

var MOD_ORDER = ${modOrder};

// Preview-only emulation of Anki's [sound:] -> replay-button conversion, so
// audio fields show the real shipped icon instead of raw token text.
function toReplayButtons(html) {
  return html.replace(/\\[sound:([^\\]]+)\\]/g, function (m, f) {
    return '<a class="replay-button soundLink" href="#" onclick="return false" aria-label="replay">[sound:' + f + ']</a>';
  });
}

function buildDoc() {
  var tpl = face === 'front' ? TPL_FRONT : TPL_BACK;
  var parts = splitTemplate(render(tpl, SAMPLE));
  parts.html = toReplayButtons(parts.html);
  var modsHtml = MOD_ORDER.map(function (name) {
    return '<script>' + HNA_MODS[name] + '<\\/script>';
  }).join('\\n');
  var pre = '<script>' +
    'window.__hnaTypedAnswerBuffer = ' + JSON.stringify(face === 'back' ? SAMPLE_TYPED : '') + ';' +
    'window.__hnaCardType = ' + JSON.stringify(lastMode) + ';' +
    '<\\/script>';
  var nightClass = nightMode ? ' night-mode' : '';
  return '<!DOCTYPE html><html class="' + (nightMode ? 'night-mode' : '') + '"><head><meta charset="utf-8">' +
    '<style>' + HNA_CSS + ' body.hna-preview #qa .sound a.replay-button.soundLink { color: transparent; font-size: 0; }<\/style></head><body class="hna-preview' + nightClass + '">' +
    '<div id="qa">' + parts.html + '</div>' + pre + modsHtml +
    '<script>' + parts.inline.join(';\\n') + ';(function(){var input=document.getElementById("typeans");if(input)input.disabled=true;})();<\\/script>' +
    '</body></html>';
}

function renderStage() {
  stage.srcdoc = buildDoc();
}

// The typing preview is a visual layout review surface for BOTH faces. Typing,
// settings, and review-state controls still belong to Anki, so the input is
// inert here; the back face renders with a sample typed buffer so the visual
// diff is visible. There is deliberately no shuffle control.

// ── Face / night-mode / width wiring (no shuffle) ──
document.getElementById('bFront').onclick = function () {
  face = 'front';
  this.classList.add('on');
  document.getElementById('bBack').classList.remove('on');
  renderStage();
};
document.getElementById('bBack').onclick = function () {
  face = 'back';
  this.classList.add('on');
  document.getElementById('bFront').classList.remove('on');
  renderStage();
};
document.getElementById('bNight').onclick = function () {
  nightMode = !nightMode;
  this.classList.toggle('on', nightMode);
  renderStage();
};

Array.prototype.forEach.call(document.querySelectorAll('[data-w]'), function (btn) {
  btn.addEventListener('click', function () {
    Array.prototype.forEach.call(document.querySelectorAll('[data-w]'), function (b) { b.classList.remove('on'); });
    btn.classList.add('on');
    var w = Number(btn.getAttribute('data-w'));
    stage.className = w ? 'w' + w : '';
  });
});

renderStage();
</script>
</body>
</html>
`;

fs.writeFileSync(OUT, preview, 'utf8');
console.log('preview generated -> ' + OUT + '  (root: ' + ROOT + ')');
